### ISSUE TITLE
Value of av doesn't change anything for the render + td doesn't work

### ISSUE THREAD

**Issue by LucasColas** [Dashstrom/tp-antlr#3]
Hello,
I tried to run a program, but the render is not good. The value given to the exp av doesn't change anything. The line will be the same length. Also, td doesn't work. I have `td 90` in my program but the orientation of the line is not good.
Here's a a screenshot of the render : 
![Capture d'écran 2024-04-21 102351](https://github.com/Dashstrom/tp-antlr/assets/51634013/09c99e93-fb1c-4ad8-946d-97e353e9f3f2)

**Comment by Dashstrom** [comment]
I will investigate, even if I think it comes from the original tp

**Comment by Dashstrom** [comment]
I made mistakes when renaming inity variables to camelcase initY as the convention says in java 🤡

**Comment by LucasColas** [comment]
Did you fix it ? 
With the original TP the render is working : 
![Capture d'écran 2024-04-21 115017](https://github.com/Dashstrom/tp-antlr/assets/51634013/b39c32f9-10d9-41c1-a7a6-087fd81443b6)

**Comment by Dashstrom** [comment]
Yes !
![image](https://github.com/Dashstrom/tp-antlr/assets/60299112/109226e5-df5f-4ba8-a1ca-f9535fde242b)

**Comment by LucasColas** [comment]
Awesome !
